-- 股票：stock_price_features和financial_statement_features合并
    -- finiancial_statement_features：年度
-- 行业：industry_summary_daily/monthly/yearly
-- 一个宏观指标的表 macro_index
    -- 月度
-- step1. 合并表格 
-- step2. 筛选不必要的年份

CREATE TABLE combined_table_1 AS
(
SELECT
    sp.`Date` AS sp_Date,
    fs.`Date` AS fs_Date,
    ind.`Date` AS ind_Date,
    m.`Date` AS m_Date,
    fs.`Symbol` AS fs_Symbol,
    sp.`Symbol` AS sp_Symbol,
    ind.`GICS_id`,
    sp.`Industry` AS sp_Industry,
    sp.`Open` AS sp_Open,
    sp.`High` AS sp_High,
    sp.`Low` AS sp_Low,
    sp.`Close` AS sp_Close,
    sp.`Adj_Close` AS sp_Adj_Close,
    sp.`Volume` AS sp_Volume,
    sp.`1d_rt` AS sp_1d_rt,
    sp.`5d_rt` AS sp_5d_rt,
    sp.`22d_rt` AS sp_22d_rt,
    sp.`stock_5d_MA` AS sp_stock_5d_MA,
    sp.`stock_22d_MA` AS sp_stock_22d_MA,
    sp.`vol_1d_pct` AS sp_vol_1d_pct,
    sp.`vol_5d_pct` AS sp_vol_5d_pct,
    sp.`vol_22d_pct` AS sp_vol_22d_pct,
    sp.`vol_5d_MA` AS sp_vol_5d_MA,
    sp.`vol_22d_MA` AS sp_vol_22d_MA,
    sp.`stock_5d_std` AS sp_stock_5d_std,
    sp.`stock_22d_std` AS sp_stock_22d_std,
    sp.`vol_5d_std` AS sp_vol_5d_std,
    sp.`vol_22d_std` AS sp_vol_22d_std,
    sp.`search_popularity` AS sp_search_popularity,
    sp.`ESG_score` AS sp_ESG_score,
    sp.`E_score` AS sp_E_score,
    sp.`S_score` AS sp_S_score,
    sp.`G_score` AS sp_G_score,
    sp.`Sentiment_scores` AS sp_Sentiment_scores,
    fs.`Industry` AS fs_Industry,
    fs.`Tax_Effect_Of_Unusual_Items`,
    fs.`Tax_Rate_For_Calcs`,
    fs.`Net_Income_From_Continuing_Operation_Net_Minority_Interest`,
    fs.`Reconciled_Depreciation`,
    fs.`Net_Interest_Income`,
    fs.`Interest_Expense`,
    fs.`Normalized_Income`,
    fs.`Net_Income_From_Continuing_And_Discontinued_Operation`,
    fs.`Diluted_NI_Availto_Com_Stockholders`,
    fs.`Net_Income_Common_Stockholders`,
    fs.`Net_Income`,
    fs.`Net_Income_Including_Noncontrolling_Interests`,
    fs.`Net_Income_Continuous_Operations`,
    fs.`Tax_Provision`,
    fs.`Pretax_Income`,
    fs.`Total_Revenue`,
    fs.`Operating_Revenue`,
    fs.`Ordinary_Shares_Number`,
    fs.`Share_Issued`,
    fs.`Total_Debt`,
    fs.`Tangible_Book_Value`,
    fs.`Invested_Capital`,
    fs.`Net_Tangible_Assets`,
    fs.`Common_Stock_Equity`,
    fs.`Total_Capitalization`,
    fs.`Total_Equity_Gross_Minority_Interest`,
    fs.`Stockholders_Equity`,
    fs.`Gains_Losses_Not_Affecting_Retained_Earnings`,
    fs.`Retained_Earnings`,
    fs.`Capital_Stock`,
    fs.`Common_Stock`,
    fs.`Total_Liabilities_Net_Minority_Interest`,
    fs.`Long_Term_Debt_And_Capital_Lease_Obligation`,
    fs.`Long_Term_Debt`,
    fs.`Payables_And_Accrued_Expenses`,
    fs.`Total_Assets`,
    fs.`Net_PPE`,
    fs.`Receivables`,
    fs.`Accounts_Receivable`,
    fs.`Cash_And_Cash_Equivalents`,
    fs.`Free_Cash_Flow`,
    fs.`Repayment_Of_Debt`,
    fs.`End_Cash_Position`,
    fs.`Beginning_Cash_Position`,
    fs.`Changes_In_Cash`,
    fs.`Financing_Cash_Flow`,
    fs.`Cash_Flow_From_Continuing_Financing_Activities`,
    fs.`Net_Issuance_Payments_Of_Debt`,
    fs.`Net_Long_Term_Debt_Issuance`,
    fs.`Long_Term_Debt_Payments`,
    fs.`Investing_Cash_Flow`,
    fs.`Cash_Flow_From_Continuing_Investing_Activities`,
    fs.`Operating_Cash_Flow`,
    fs.`Cash_Flow_From_Continuing_Operating_Activities`,
    fs.`Change_In_Working_Capital`,
    fs.`Change_In_Receivables`,
    fs.`Net_Income_From_Continuing_Operations`,
    fs.`Net_Profit_Margin`,
    fs.`Capital_Structure_Ratio`,
    fs.`Equity_Ratio`,
    fs.`Cash_Liquidity_Ratio`,
    fs.`Accounts_Recievable_Turnover`,
    fs.`Total_Assets_Turnover`,
    fs.`Financial_Leverage`,
    fs.`PCA_C0`,
    fs.`PCA_C1`,
    fs.`PCA_C2`,
    fs.`PCA_C3`,
    fs.`PCA_C4`,
    fs.`PCA_C5`,
    fs.`PCA_C6`,
    fs.`PCA_C7`,
    fs.`PCA_C8`,
    fs.`PCA_C9`,
    ind.`ETF_Type`,
    ind.`ETF_5dMA`,
    ind.`ETF_22dMA`,
    ind.`ETF_5dstd`,
    ind.`ETF_22std`,
    ind.`1d_rt` AS ind_1d_rt,
    ind.`5d_rt` AS ind_5d_rt,
    ind.`22d_rt` AS ind_22d_rt,
    ind.`Vol_5dMA`,
    ind.`Vol_22dMA`,
    ind.`Vol_1d_pct`,
    ind.`Vol_5d_pct`,
    ind.`Vol_5dstd`,
    ind.`Vol_22dstd`,
    m.CPI,
    m.CPI_YoY,
    m.Core_CPI,
    m.Core_CPI_YoY,
    m.PPI,
    m.PPI_YoY,
    m.Retailers_Inventories_Sales_Ratio,
    m.Retailers_YoY,
    m.Total_Buz_Inventories_Sales_Ratio,
    m.Total_Buz_YoY,
    m.Unemployment_Rate,
    m.Target_rate_discounted,
    m.Target_range_upper_limit,
    m.Target_range_louwer_limit,
    m.CPI_QoQ,
    m.Core_CPI_QoQ,
    m.PPI_QoQ,
    m.Retailers_Inventories_Sales_Ratio_QoQ,
    m.Total_Buz_Inventories_Sales_Ratio_QoQ,
    m.Unemployment_Rate_QoQ
FROM stock_price_features sp
LEFT JOIN financial_statement_features fs ON YEAR(sp.`Date`) = YEAR(fs.`Date`) AND sp.`Symbol` = fs.`Symbol`
LEFT JOIN industry_summary_daily ind ON sp.`Industry` = ind.`GICS_id` AND DATE(sp.`Date`) = DATE(ind.`Date`)
LEFT JOIN macro_index m ON DATE_FORMAT(sp.`Date`,'%Y%m') = DATE_FORMAT(m.Date,'%Y%m')
)


SELECT * FROM combined_table_1
WHERE YEAR(sp_Date) >= 2020
LIMIT 100;


